services:
  store-database:
    image: postgres:15
    ports:
      - "${DB_PORT}:5432"
    #volumes:
      #- ./store-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${DB_NAME}",  "-U", "${DB_USER}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  store-migration:
    build:
      context: ./store-backend
      target: makemigration
      dockerfile: ./Dockerfile
    depends_on:
      store-database:
        condition: service_healthy
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
  store-backend:
    build:
      context: ./store-backend
      target: dev
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./store-backend/src:/app/src
      - ./store-backend/tests:/app/tests
      - ./store-backend/alembic:/app/alembic
      - ./store-backend/alembic.ini:/app/alembic.ini
      - ./store-backend/pyproject.toml:/app/pyproject.toml
      - ./store-backend/poetry.lock:/app/poetry.lock
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      store-migration:
        condition: service_completed_successfully
    healthcheck:
      test: >
         sh -c "curl -f http://localhost:8000/Categories"
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
  store-frontend:
    build:
      context: ./store-frontend
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./store-frontend/src:/app/src
    