name: Frontend CI

on:
    pull_request:
        paths:
            - 'store-frontend/**'

jobs:
    test-frontend:
        runs-on: ubuntu-latest
        steps:
            - name: Repository's checkout
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 22

            - name: Install Dependencies
              run: |
                cd store-frontend
                npm ci

            - name: Run tests
              run: |
                cd store-frontend
                npm run test
                npm run build